# Queue types
QUEUE_USER_BURIED = -3
QUEUE_SCHED_BURIED = -2
QUEUE_SUSPENDED = -1
QUEUE_NEW = 0
QUEUE_LRN = 1
QUEUE_REV = 2
QUEUE_DAY_LRN = 3
QUEUE_PREVIEW = 4

# Card types
CARD_NEW = 0
CARD_LRN = 1
CARD_DUE = 2
CARD_RELRN = 3 #schev v2 only
